repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.9
  #- repo: https://github.com/pre-commit/pre-commit-hooks
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
      - id: flake8
  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    rev: ''
    hooks:
      - id: prettier
        exclude: 'templates/|mockups/|README.md'
