# Generated by Django 3.1.3 on 2020-12-10 13:16

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipient",
            constraint=models.UniqueConstraint(
                fields=("user", "message"), name="uniq_recipient"
            ),
        ),
    ]
